# Generated by Django 4.2.11 on 2024-04-11 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import pedidos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livro', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(max_length=20)),
                ('status', enumfields.fields.EnumField(default='PagamentoPendente', enum=pedidos.models.StatusPedido, max_length=20)),
                ('forma_de_pagamento', enumfields.fields.EnumField(default='Cartão de crétido', enum=pedidos.models.FormaPagamento, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarrinhoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_hora_item_criado', models.DateTimeField(auto_now_add=True)),
                ('data_hora_item_atualizado', models.DateTimeField(auto_now=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.carrinho')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livro')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='livros',
            field=models.ManyToManyField(through='pedidos.CarrinhoLivro', to='livro.livro'),
        ),
    ]
