# Generated by Django 4.2.11 on 2024-04-11 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livro', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='livros',
            field=models.ManyToManyField(blank=True, null=True, through='pedidos.CarrinhoLivro', to='livro.livro'),
        ),
        migrations.AlterField(
            model_name='carrinholivro',
            name='carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.carrinho'),
        ),
        migrations.AlterField(
            model_name='carrinholivro',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livro.livro'),
        ),
        migrations.AlterField(
            model_name='carrinholivro',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
