# Generated by Django 5.0.3 on 2024-03-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=13)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('senha', models.CharField(max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.endereco')),
            ],
            options={
                'verbose_name': 'Cadastro de usuário',
                'verbose_name_plural': 'Cadastro de usuários',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
